[2024-05-26 21:19:23,370] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: load_init_data.extract_data_from_csv 2024-05-25T02:00:00+00:00 [queued]>
[2024-05-26 21:19:23,398] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: load_init_data.extract_data_from_csv 2024-05-25T02:00:00+00:00 [queued]>
[2024-05-26 21:19:23,399] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2024-05-26 21:19:23,399] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2024-05-26 21:19:23,400] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2024-05-26 21:19:23,408] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): extract_data_from_csv> on 2024-05-25T02:00:00+00:00
[2024-05-26 21:19:23,416] {standard_task_runner.py:52} INFO - Started process 175 to run task
[2024-05-26 21:19:23,436] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'load_init_data', 'extract_data_from_csv', '2024-05-25T02:00:00+00:00', '--job-id', '390', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/load_init_data.py', '--cfg-path', '/tmp/tmppkmpdwwk', '--error-file', '/tmp/tmph7ievh93']
[2024-05-26 21:19:23,446] {standard_task_runner.py:77} INFO - Job 390: Subtask extract_data_from_csv
[2024-05-26 21:19:23,483] {logging_mixin.py:104} INFO - Running <TaskInstance: load_init_data.extract_data_from_csv 2024-05-25T02:00:00+00:00 [running]> on host ff5273ee61d8
[2024-05-26 21:19:23,513] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=load_init_data
AIRFLOW_CTX_TASK_ID=extract_data_from_csv
AIRFLOW_CTX_EXECUTION_DATE=2024-05-25T02:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-25T02:00:00+00:00
[2024-05-26 21:19:23,519] {taskinstance.py:1455} ERROR - [Errno 2] No such file or directory: 'init_dataset.csv'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_init_data.py", line 19, in extract_data_from_csv
    data = pd.read_csv("init_dataset.csv")
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 454, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 948, in __init__
    self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1180, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 2010, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] No such file or directory: 'init_dataset.csv'
[2024-05-26 21:19:23,524] {taskinstance.py:1503} INFO - Marking task as UP_FOR_RETRY. dag_id=load_init_data, task_id=extract_data_from_csv, execution_date=20240525T020000, start_date=20240526T211923, end_date=20240526T211923
[2024-05-26 21:19:23,577] {local_task_job.py:146} INFO - Task exited with return code 1
[2024-05-26 21:20:57,514] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: load_init_data.extract_data_from_csv 2024-05-25T02:00:00+00:00 [queued]>
[2024-05-26 21:20:57,526] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: load_init_data.extract_data_from_csv 2024-05-25T02:00:00+00:00 [queued]>
[2024-05-26 21:20:57,527] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2024-05-26 21:20:57,527] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2024-05-26 21:20:57,527] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2024-05-26 21:20:57,535] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): extract_data_from_csv> on 2024-05-25T02:00:00+00:00
[2024-05-26 21:20:57,539] {standard_task_runner.py:52} INFO - Started process 174 to run task
[2024-05-26 21:20:57,545] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'load_init_data', 'extract_data_from_csv', '2024-05-25T02:00:00+00:00', '--job-id', '393', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/load_init_data.py', '--cfg-path', '/tmp/tmppeafqccv', '--error-file', '/tmp/tmpqxrw_drz']
[2024-05-26 21:20:57,548] {standard_task_runner.py:77} INFO - Job 393: Subtask extract_data_from_csv
[2024-05-26 21:20:57,580] {logging_mixin.py:104} INFO - Running <TaskInstance: load_init_data.extract_data_from_csv 2024-05-25T02:00:00+00:00 [running]> on host ff5273ee61d8
[2024-05-26 21:20:57,608] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=load_init_data
AIRFLOW_CTX_TASK_ID=extract_data_from_csv
AIRFLOW_CTX_EXECUTION_DATE=2024-05-25T02:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-25T02:00:00+00:00
[2024-05-26 21:20:57,616] {taskinstance.py:1455} ERROR - [Errno 2] No such file or directory: '../../init_dataset.csv'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_init_data.py", line 19, in extract_data_from_csv
    data = pd.read_csv("../../init_dataset.csv")
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 454, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 948, in __init__
    self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1180, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 2010, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] No such file or directory: '../../init_dataset.csv'
[2024-05-26 21:20:57,620] {taskinstance.py:1503} INFO - Marking task as UP_FOR_RETRY. dag_id=load_init_data, task_id=extract_data_from_csv, execution_date=20240525T020000, start_date=20240526T212057, end_date=20240526T212057
[2024-05-26 21:20:57,641] {local_task_job.py:146} INFO - Task exited with return code 1
[2024-05-26 21:22:13,006] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: load_init_data.extract_data_from_csv 2024-05-25T02:00:00+00:00 [queued]>
[2024-05-26 21:22:13,016] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: load_init_data.extract_data_from_csv 2024-05-25T02:00:00+00:00 [queued]>
[2024-05-26 21:22:13,016] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2024-05-26 21:22:13,016] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2024-05-26 21:22:13,016] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2024-05-26 21:22:13,024] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): extract_data_from_csv> on 2024-05-25T02:00:00+00:00
[2024-05-26 21:22:13,028] {standard_task_runner.py:52} INFO - Started process 174 to run task
[2024-05-26 21:22:13,032] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'load_init_data', 'extract_data_from_csv', '2024-05-25T02:00:00+00:00', '--job-id', '397', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/load_init_data.py', '--cfg-path', '/tmp/tmpg3h2xyfv', '--error-file', '/tmp/tmpg0607bcx']
[2024-05-26 21:22:13,035] {standard_task_runner.py:77} INFO - Job 397: Subtask extract_data_from_csv
[2024-05-26 21:22:13,077] {logging_mixin.py:104} INFO - Running <TaskInstance: load_init_data.extract_data_from_csv 2024-05-25T02:00:00+00:00 [running]> on host ff5273ee61d8
[2024-05-26 21:22:13,107] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=load_init_data
AIRFLOW_CTX_TASK_ID=extract_data_from_csv
AIRFLOW_CTX_EXECUTION_DATE=2024-05-25T02:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-25T02:00:00+00:00
[2024-05-26 21:22:13,111] {taskinstance.py:1455} ERROR - [Errno 2] No such file or directory: 'init_dataset.csv'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_init_data.py", line 19, in extract_data_from_csv
    data = pd.read_csv("init_dataset.csv")
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 454, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 948, in __init__
    self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1180, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 2010, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] No such file or directory: 'init_dataset.csv'
[2024-05-26 21:22:13,115] {taskinstance.py:1503} INFO - Marking task as UP_FOR_RETRY. dag_id=load_init_data, task_id=extract_data_from_csv, execution_date=20240525T020000, start_date=20240526T212213, end_date=20240526T212213
[2024-05-26 21:22:13,131] {local_task_job.py:146} INFO - Task exited with return code 1
[2024-05-27 21:19:26,176] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: load_init_data.extract_data_from_csv 2024-05-25T02:00:00+00:00 [queued]>
[2024-05-27 21:19:26,222] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: load_init_data.extract_data_from_csv 2024-05-25T02:00:00+00:00 [queued]>
[2024-05-27 21:19:26,224] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2024-05-27 21:19:26,226] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2024-05-27 21:19:26,227] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2024-05-27 21:19:26,241] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): extract_data_from_csv> on 2024-05-25T02:00:00+00:00
[2024-05-27 21:19:26,245] {standard_task_runner.py:52} INFO - Started process 186 to run task
[2024-05-27 21:19:26,293] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'load_init_data', 'extract_data_from_csv', '2024-05-25T02:00:00+00:00', '--job-id', '498', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/load_init_data.py', '--cfg-path', '/tmp/tmpwg8xnfh3', '--error-file', '/tmp/tmpwmhrwaoi']
[2024-05-27 21:19:26,312] {standard_task_runner.py:77} INFO - Job 498: Subtask extract_data_from_csv
[2024-05-27 21:19:26,387] {logging_mixin.py:104} INFO - Running <TaskInstance: load_init_data.extract_data_from_csv 2024-05-25T02:00:00+00:00 [running]> on host 1f334d963743
[2024-05-27 21:19:26,424] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=load_init_data
AIRFLOW_CTX_TASK_ID=extract_data_from_csv
AIRFLOW_CTX_EXECUTION_DATE=2024-05-25T02:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-25T02:00:00+00:00
[2024-05-27 21:19:26,943] {python.py:118} INFO - Done. Returned value was: None
[2024-05-27 21:19:26,950] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=load_init_data, task_id=extract_data_from_csv, execution_date=20240525T020000, start_date=20240527T211926, end_date=20240527T211926
[2024-05-27 21:19:26,975] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-27 21:19:27,011] {local_task_job.py:146} INFO - Task exited with return code 0
[2024-05-28 16:24:17,465] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: load_init_data.extract_data_from_csv 2024-05-25T02:00:00+00:00 [queued]>
[2024-05-28 16:24:17,484] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: load_init_data.extract_data_from_csv 2024-05-25T02:00:00+00:00 [queued]>
[2024-05-28 16:24:17,485] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2024-05-28 16:24:17,485] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2024-05-28 16:24:17,485] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2024-05-28 16:24:17,493] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): extract_data_from_csv> on 2024-05-25T02:00:00+00:00
[2024-05-28 16:24:17,497] {standard_task_runner.py:52} INFO - Started process 196 to run task
[2024-05-28 16:24:17,507] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'load_init_data', 'extract_data_from_csv', '2024-05-25T02:00:00+00:00', '--job-id', '508', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/load_init_data.py', '--cfg-path', '/tmp/tmpgi1fbv9n', '--error-file', '/tmp/tmph8bkxl4u']
[2024-05-28 16:24:17,512] {standard_task_runner.py:77} INFO - Job 508: Subtask extract_data_from_csv
[2024-05-28 16:24:17,559] {logging_mixin.py:104} INFO - Running <TaskInstance: load_init_data.extract_data_from_csv 2024-05-25T02:00:00+00:00 [running]> on host a3c9b0e21f74
[2024-05-28 16:24:17,602] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=load_init_data
AIRFLOW_CTX_TASK_ID=extract_data_from_csv
AIRFLOW_CTX_EXECUTION_DATE=2024-05-25T02:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-25T02:00:00+00:00
[2024-05-28 16:24:18,028] {python.py:118} INFO - Done. Returned value was: None
[2024-05-28 16:24:18,038] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=load_init_data, task_id=extract_data_from_csv, execution_date=20240525T020000, start_date=20240528T162417, end_date=20240528T162418
[2024-05-28 16:24:18,114] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-28 16:24:18,136] {local_task_job.py:146} INFO - Task exited with return code 0
[2024-06-09 14:01:21,104] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: load_init_data.extract_data_from_csv 2024-05-25T02:00:00+00:00 [queued]>
[2024-06-09 14:01:21,181] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: load_init_data.extract_data_from_csv 2024-05-25T02:00:00+00:00 [queued]>
[2024-06-09 14:01:21,182] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2024-06-09 14:01:21,189] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2024-06-09 14:01:21,191] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2024-06-09 14:01:21,215] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): extract_data_from_csv> on 2024-05-25T02:00:00+00:00
[2024-06-09 14:01:21,247] {standard_task_runner.py:52} INFO - Started process 185 to run task
[2024-06-09 14:01:21,257] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'load_init_data', 'extract_data_from_csv', '2024-05-25T02:00:00+00:00', '--job-id', '10', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/load_init_data.py', '--cfg-path', '/tmp/tmpeqxgkygc', '--error-file', '/tmp/tmpf4iuedlk']
[2024-06-09 14:01:21,283] {standard_task_runner.py:77} INFO - Job 10: Subtask extract_data_from_csv
[2024-06-09 14:01:21,488] {logging_mixin.py:104} INFO - Running <TaskInstance: load_init_data.extract_data_from_csv 2024-05-25T02:00:00+00:00 [running]> on host 97b873bf6d4d
[2024-06-09 14:01:21,620] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=load_init_data
AIRFLOW_CTX_TASK_ID=extract_data_from_csv
AIRFLOW_CTX_EXECUTION_DATE=2024-05-25T02:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-25T02:00:00+00:00
[2024-06-09 14:01:23,323] {python.py:118} INFO - Done. Returned value was: None
[2024-06-09 14:01:23,450] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=load_init_data, task_id=extract_data_from_csv, execution_date=20240525T020000, start_date=20240609T140121, end_date=20240609T140123
[2024-06-09 14:01:24,083] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-09 14:01:24,154] {local_task_job.py:146} INFO - Task exited with return code 0
