[2024-05-26 21:24:16,695] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: load_init_data.save_into_db 2024-05-24T02:00:00+00:00 [queued]>
[2024-05-26 21:24:16,706] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: load_init_data.save_into_db 2024-05-24T02:00:00+00:00 [queued]>
[2024-05-26 21:24:16,708] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2024-05-26 21:24:16,708] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2024-05-26 21:24:16,709] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2024-05-26 21:24:16,728] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): save_into_db> on 2024-05-24T02:00:00+00:00
[2024-05-26 21:24:16,735] {standard_task_runner.py:52} INFO - Started process 179 to run task
[2024-05-26 21:24:16,739] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'load_init_data', 'save_into_db', '2024-05-24T02:00:00+00:00', '--job-id', '401', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/load_init_data.py', '--cfg-path', '/tmp/tmpxi_a9_aa', '--error-file', '/tmp/tmpztyb9uwd']
[2024-05-26 21:24:16,742] {standard_task_runner.py:77} INFO - Job 401: Subtask save_into_db
[2024-05-26 21:24:16,807] {logging_mixin.py:104} INFO - Running <TaskInstance: load_init_data.save_into_db 2024-05-24T02:00:00+00:00 [running]> on host ff5273ee61d8
[2024-05-26 21:24:16,852] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=load_init_data
AIRFLOW_CTX_TASK_ID=save_into_db
AIRFLOW_CTX_EXECUTION_DATE=2024-05-24T02:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-24T02:00:00+00:00
[2024-05-26 21:24:17,380] {python.py:118} INFO - Done. Returned value was: None
[2024-05-26 21:24:17,391] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=load_init_data, task_id=save_into_db, execution_date=20240524T020000, start_date=20240526T212416, end_date=20240526T212417
[2024-05-26 21:24:17,420] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-26 21:24:17,460] {local_task_job.py:146} INFO - Task exited with return code 0
[2024-06-09 14:02:34,473] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: load_init_data.save_into_db 2024-05-24T02:00:00+00:00 [queued]>
[2024-06-09 14:02:34,617] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: load_init_data.save_into_db 2024-05-24T02:00:00+00:00 [queued]>
[2024-06-09 14:02:34,637] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2024-06-09 14:02:34,645] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2024-06-09 14:02:34,649] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2024-06-09 14:02:34,702] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): save_into_db> on 2024-05-24T02:00:00+00:00
[2024-06-09 14:02:34,708] {standard_task_runner.py:52} INFO - Started process 282 to run task
[2024-06-09 14:02:34,720] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'load_init_data', 'save_into_db', '2024-05-24T02:00:00+00:00', '--job-id', '52', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/load_init_data.py', '--cfg-path', '/tmp/tmpxszetw26', '--error-file', '/tmp/tmpev2fpxxd']
[2024-06-09 14:02:34,724] {standard_task_runner.py:77} INFO - Job 52: Subtask save_into_db
[2024-06-09 14:02:35,172] {logging_mixin.py:104} INFO - Running <TaskInstance: load_init_data.save_into_db 2024-05-24T02:00:00+00:00 [running]> on host 97b873bf6d4d
[2024-06-09 14:02:35,480] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=load_init_data
AIRFLOW_CTX_TASK_ID=save_into_db
AIRFLOW_CTX_EXECUTION_DATE=2024-05-24T02:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-24T02:00:00+00:00
[2024-06-09 14:02:36,086] {python.py:118} INFO - Done. Returned value was: None
[2024-06-09 14:02:36,119] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=load_init_data, task_id=save_into_db, execution_date=20240524T020000, start_date=20240609T140234, end_date=20240609T140236
[2024-06-09 14:02:36,176] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-09 14:02:36,230] {local_task_job.py:77} ERROR - Received SIGTERM. Terminating subprocesses
