[2024-05-26 16:37:10,614] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: get_new_data.scrap_cnn 2024-05-21T00:00:00+00:00 [queued]>
[2024-05-26 16:37:10,623] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: get_new_data.scrap_cnn 2024-05-21T00:00:00+00:00 [queued]>
[2024-05-26 16:37:10,624] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2024-05-26 16:37:10,626] {taskinstance.py:1043} INFO - Starting attempt 2 of 6
[2024-05-26 16:37:10,626] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2024-05-26 16:37:10,640] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): scrap_cnn> on 2024-05-21T00:00:00+00:00
[2024-05-26 16:37:10,656] {standard_task_runner.py:52} INFO - Started process 194 to run task
[2024-05-26 16:37:10,663] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'get_new_data', 'scrap_cnn', '2024-05-21T00:00:00+00:00', '--job-id', '195', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/get_new_data.py', '--cfg-path', '/tmp/tmp7h2ww4z8', '--error-file', '/tmp/tmpn31isb_8']
[2024-05-26 16:37:10,670] {standard_task_runner.py:77} INFO - Job 195: Subtask scrap_cnn
[2024-05-26 16:37:10,727] {logging_mixin.py:104} INFO - Running <TaskInstance: get_new_data.scrap_cnn 2024-05-21T00:00:00+00:00 [running]> on host 6a7718113559
[2024-05-26 16:37:10,775] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_new_data
AIRFLOW_CTX_TASK_ID=scrap_cnn
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T00:00:00+00:00
[2024-05-26 16:37:15,730] {local_task_job.py:188} WARNING - State of this instance has been externally set to None. Terminating instance.
[2024-05-26 16:37:15,735] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 194
[2024-05-26 16:37:15,737] {taskinstance.py:1239} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-05-26 16:37:15,745] {taskinstance.py:1455} ERROR - Task received SIGTERM signal
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/get_new_data.py", line 17, in scrap_cnn
    response = requests.get('http://cnn_scrapper:7010/extract_news')
  File "/home/airflow/.local/lib/python3.6/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/airflow/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/airflow/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.6/http/client.py", line 1383, in getresponse
    response.begin()
  File "/usr/local/lib/python3.6/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.6/http/client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1241, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-05-26 16:37:15,755] {taskinstance.py:1503} INFO - Marking task as UP_FOR_RETRY. dag_id=get_new_data, task_id=scrap_cnn, execution_date=20240521T000000, start_date=20240526T163710, end_date=20240526T163715
[2024-05-26 16:37:15,798] {process_utils.py:66} INFO - Process psutil.Process(pid=194, status='terminated', exitcode=1, started='16:37:10') (194) terminated with exit code 1
