[2024-05-26 16:59:43,261] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: get_new_data.transform 2024-05-07T00:00:00+00:00 [queued]>
[2024-05-26 16:59:43,269] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: get_new_data.transform 2024-05-07T00:00:00+00:00 [queued]>
[2024-05-26 16:59:43,269] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2024-05-26 16:59:43,270] {taskinstance.py:1043} INFO - Starting attempt 4 of 6
[2024-05-26 16:59:43,270] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2024-05-26 16:59:43,279] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): transform> on 2024-05-07T00:00:00+00:00
[2024-05-26 16:59:43,282] {standard_task_runner.py:52} INFO - Started process 538 to run task
[2024-05-26 16:59:43,286] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'get_new_data', 'transform', '2024-05-07T00:00:00+00:00', '--job-id', '276', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/get_new_data.py', '--cfg-path', '/tmp/tmp56pgl_qg', '--error-file', '/tmp/tmpb6mtmgy3']
[2024-05-26 16:59:43,288] {standard_task_runner.py:77} INFO - Job 276: Subtask transform
[2024-05-26 16:59:43,321] {logging_mixin.py:104} INFO - Running <TaskInstance: get_new_data.transform 2024-05-07T00:00:00+00:00 [running]> on host 6a7718113559
[2024-05-26 16:59:43,353] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_new_data
AIRFLOW_CTX_TASK_ID=transform
AIRFLOW_CTX_EXECUTION_DATE=2024-05-07T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-07T00:00:00+00:00
[2024-05-26 16:59:43,411] {taskinstance.py:1455} ERROR - Object of type 'DataFrame' is not JSON serializable
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/get_new_data.py", line 37, in transform
    response = requests.post('http://data_transformer:7050/transform', json={'data': data, 'column': 'text'})
  File "/home/airflow/.local/lib/python3.6/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/home/airflow/.local/lib/python3.6/site-packages/requests/sessions.py", line 466, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/airflow/.local/lib/python3.6/site-packages/requests/models.py", line 319, in prepare
    self.prepare_body(data, files, json)
  File "/home/airflow/.local/lib/python3.6/site-packages/requests/models.py", line 469, in prepare_body
    body = complexjson.dumps(json)
  File "/usr/local/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'DataFrame' is not JSON serializable
[2024-05-26 16:59:43,414] {taskinstance.py:1503} INFO - Marking task as UP_FOR_RETRY. dag_id=get_new_data, task_id=transform, execution_date=20240507T000000, start_date=20240526T165943, end_date=20240526T165943
[2024-05-26 16:59:43,511] {local_task_job.py:146} INFO - Task exited with return code 1
