[2024-05-27 00:02:26,646] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: get_new_data.scrap_cnn 2024-05-26T00:00:00+00:00 [queued]>
[2024-05-27 00:02:26,658] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: get_new_data.scrap_cnn 2024-05-26T00:00:00+00:00 [queued]>
[2024-05-27 00:02:26,658] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2024-05-27 00:02:26,659] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2024-05-27 00:02:26,659] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2024-05-27 00:02:26,666] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): scrap_cnn> on 2024-05-26T00:00:00+00:00
[2024-05-27 00:02:26,670] {standard_task_runner.py:52} INFO - Started process 937 to run task
[2024-05-27 00:02:26,674] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'get_new_data', 'scrap_cnn', '2024-05-26T00:00:00+00:00', '--job-id', '464', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/get_new_data.py', '--cfg-path', '/tmp/tmpwzy4ib3n', '--error-file', '/tmp/tmpa2gc_yxv']
[2024-05-27 00:02:26,676] {standard_task_runner.py:77} INFO - Job 464: Subtask scrap_cnn
[2024-05-27 00:02:26,713] {logging_mixin.py:104} INFO - Running <TaskInstance: get_new_data.scrap_cnn 2024-05-26T00:00:00+00:00 [running]> on host 1f334d963743
[2024-05-27 00:02:26,748] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_new_data
AIRFLOW_CTX_TASK_ID=scrap_cnn
AIRFLOW_CTX_EXECUTION_DATE=2024-05-26T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-26T00:00:00+00:00
[2024-05-27 00:12:30,235] {local_task_job.py:188} WARNING - State of this instance has been externally set to up_for_retry. Terminating instance.
[2024-05-27 00:12:30,243] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 937
[2024-05-27 00:12:30,248] {taskinstance.py:1239} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-05-27 00:12:30,288] {taskinstance.py:1455} ERROR - Task received SIGTERM signal
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/get_new_data.py", line 20, in scrap_cnn
    response = requests.get(cnn_scrapper_url + '/extract_news')
  File "/home/airflow/.local/lib/python3.6/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/airflow/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/airflow/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.6/http/client.py", line 1383, in getresponse
    response.begin()
  File "/usr/local/lib/python3.6/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.6/http/client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1241, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-05-27 00:12:30,344] {taskinstance.py:1503} INFO - Marking task as UP_FOR_RETRY. dag_id=get_new_data, task_id=scrap_cnn, execution_date=20240526T000000, start_date=20240527T000226, end_date=20240527T001230
[2024-05-27 00:12:30,386] {process_utils.py:66} INFO - Process psutil.Process(pid=937, status='terminated', exitcode=1, started='00:02:26') (937) terminated with exit code 1
[2024-05-28 16:24:18,875] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: get_new_data.scrap_cnn 2024-05-26T00:00:00+00:00 [queued]>
[2024-05-28 16:24:18,893] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: get_new_data.scrap_cnn 2024-05-26T00:00:00+00:00 [queued]>
[2024-05-28 16:24:18,894] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2024-05-28 16:24:18,896] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2024-05-28 16:24:18,896] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2024-05-28 16:24:18,908] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): scrap_cnn> on 2024-05-26T00:00:00+00:00
[2024-05-28 16:24:18,925] {standard_task_runner.py:52} INFO - Started process 210 to run task
[2024-05-28 16:24:18,929] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'get_new_data', 'scrap_cnn', '2024-05-26T00:00:00+00:00', '--job-id', '513', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/get_new_data.py', '--cfg-path', '/tmp/tmp0wr7cfh7', '--error-file', '/tmp/tmp2q7__889']
[2024-05-28 16:24:18,934] {standard_task_runner.py:77} INFO - Job 513: Subtask scrap_cnn
[2024-05-28 16:24:18,989] {logging_mixin.py:104} INFO - Running <TaskInstance: get_new_data.scrap_cnn 2024-05-26T00:00:00+00:00 [running]> on host a3c9b0e21f74
[2024-05-28 16:24:19,035] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_new_data
AIRFLOW_CTX_TASK_ID=scrap_cnn
AIRFLOW_CTX_EXECUTION_DATE=2024-05-26T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-26T00:00:00+00:00
[2024-05-28 16:25:44,930] {local_task_job.py:188} WARNING - State of this instance has been externally set to None. Terminating instance.
[2024-05-28 16:25:44,940] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 210
[2024-05-28 16:25:44,945] {taskinstance.py:1239} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-05-28 16:25:44,988] {taskinstance.py:1455} ERROR - Task received SIGTERM signal
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/get_new_data.py", line 20, in scrap_cnn
    response = requests.get(cnn_scrapper_url + '/extract_news')
  File "/home/airflow/.local/lib/python3.6/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/airflow/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/airflow/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.6/http/client.py", line 1383, in getresponse
    response.begin()
  File "/usr/local/lib/python3.6/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.6/http/client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1241, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-05-28 16:25:44,995] {taskinstance.py:1503} INFO - Marking task as UP_FOR_RETRY. dag_id=get_new_data, task_id=scrap_cnn, execution_date=20240526T000000, start_date=20240528T162418, end_date=20240528T162544
[2024-05-28 16:25:45,080] {process_utils.py:66} INFO - Process psutil.Process(pid=210, status='terminated', exitcode=1, started='16:24:18') (210) terminated with exit code 1
[2024-06-09 14:22:12,329] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: get_new_data.scrap_cnn 2024-05-26T00:00:00+00:00 [queued]>
[2024-06-09 14:22:12,420] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: get_new_data.scrap_cnn 2024-05-26T00:00:00+00:00 [queued]>
[2024-06-09 14:22:12,423] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2024-06-09 14:22:12,428] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2024-06-09 14:22:12,430] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2024-06-09 14:22:12,466] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): scrap_cnn> on 2024-05-26T00:00:00+00:00
[2024-06-09 14:22:12,541] {standard_task_runner.py:52} INFO - Started process 216 to run task
[2024-06-09 14:22:12,552] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'get_new_data', 'scrap_cnn', '2024-05-26T00:00:00+00:00', '--job-id', '69', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/get_new_data.py', '--cfg-path', '/tmp/tmpbu6vkts_', '--error-file', '/tmp/tmpq5lrpvxx']
[2024-06-09 14:22:12,579] {standard_task_runner.py:77} INFO - Job 69: Subtask scrap_cnn
[2024-06-09 14:22:12,756] {logging_mixin.py:104} INFO - Running <TaskInstance: get_new_data.scrap_cnn 2024-05-26T00:00:00+00:00 [running]> on host 05b5c9495664
[2024-06-09 14:22:12,924] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_new_data
AIRFLOW_CTX_TASK_ID=scrap_cnn
AIRFLOW_CTX_EXECUTION_DATE=2024-05-26T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-26T00:00:00+00:00
[2024-06-09 14:23:23,455] {local_task_job.py:188} WARNING - State of this instance has been externally set to None. Terminating instance.
[2024-06-09 14:23:23,465] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 216
[2024-06-09 14:23:23,475] {taskinstance.py:1239} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-06-09 14:23:23,589] {taskinstance.py:1455} ERROR - Task received SIGTERM signal
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/get_new_data.py", line 21, in scrap_cnn
    response = requests.get(cnn_scrapper_url + '/extract_news')
  File "/home/airflow/.local/lib/python3.6/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/airflow/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/airflow/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.6/http/client.py", line 1383, in getresponse
    response.begin()
  File "/usr/local/lib/python3.6/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.6/http/client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1241, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-06-09 14:23:23,605] {taskinstance.py:1503} INFO - Marking task as UP_FOR_RETRY. dag_id=get_new_data, task_id=scrap_cnn, execution_date=20240526T000000, start_date=20240609T142212, end_date=20240609T142323
[2024-06-09 14:23:23,695] {process_utils.py:66} INFO - Process psutil.Process(pid=216, status='terminated', exitcode=1, started='14:22:12') (216) terminated with exit code 1
